[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "segyviewer"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "PySide6",
    "pyqtgraph",
    "segyio",
]

[project.optional-dependencies]
dev = [
    "pytest>=8",
]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "app*",
    "ui*",
    "segy*",
    "plotting*",
    "processing*",
]
exclude = [
    "tests*",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]